services:
  pg_db:
    image: postgres:13.4-alpine
    container_name: postgres_db
    ports:
      - "5432:5432"
    env_file:
      - .env

  mongodb:
    container_name: "mongodb"
    image: mongo
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./mongo:/data/db
    ports:
      - "27017:27017"
    restart: always