version: '3.10'

services:
  mongodb:
    container_name: "mongodb"
    image: mongo
    environment:
      - PUID=1000
      - PGID=1000
    env_file:
      - ./src/.env
    volumes:
      - ./mongo:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "27017:27017"
    restart: always
    command: mongod --auth
    networks:
      - backend

  ugc2:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: ugc2
    env_file:
      - ./src/.env
    depends_on:
      - mongodb
      - logstash
      - kibana
      - elasticsearch
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ugc.rule=Host(`localhost`)"
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: "nginx_ugc"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/api.conf:/etc/nginx/conf.d/api.conf
      - /tmp/logs/nginx/:/var/log/nginx/
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://localhost:5044'
        tag: nginx
    depends_on:
      - ugc2
    ports:
      - "81:81"
    networks:
      - backend


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - /tmp/esdata:/tmp/elasticsearch/data
    networks:
      - backend


  logstash:
    image: docker.elastic.co/logstash/logstash:7.14.2
    environment:
      ES_HOST: "elasticsearch:9200"
      XPACK_MONITORING_ENABLED: "false"
    ports:
      - "5044:5044/udp"
    volumes:
      - ./deploy/logstash.conf:/config/logstash.conf:ro
      - /tmp/logs/nginx/:/var/log/nginx/:ro
    command: logstash -f /config/logstash.conf
    depends_on:
      - elasticsearch
    networks:
      - backend

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.2
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - backend

networks:
  backend:
    driver: bridge