version: '3.10'

services:
  mongodb:
    container_name: "mongodb"
    image: mongo
    environment:
      - PUID=1000
      - PGID=1000
    env_file:
      - ./src/.env
    volumes:
      - ./mongo:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "27017:27017"
    restart: always
    command: mongod --auth
    networks:
      - backend

  ugc2:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: ugc2
    env_file:
      - ./src/.env
    depends_on:
      - mongodb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ugc.rule=Host(`localhost`)"
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: "nginx_ugc"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/api.conf:/etc/nginx/conf.d/api.conf
    depends_on:
      - ugc2
    ports:
      - "81:81"
    networks:
      - backend


networks:
  backend:
    driver: bridge