name: UGC CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create folders for report
      run: |
          mkdir -p reports/wemake-python-styleguide
          mkdir -p reports/mypy

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install lxml==4.9.0
        pip install mypy==0.961
        pip install flake8-html==0.4.2
        pip install wemake-python-styleguide==0.16.1

    - name: Lint with wemake-python-styleguide
      run: |
        flake8 /src --exit-zero --format=html --htmldir=reports/wemake-python-styleguide/
    - name: Lint with mypy
      run: |
        mypy --html-report reports/mypy/ /src/* || true
    - name: TG Report
      uses: "appleboy/telegram-action@master"
      with:
        to: ${{secrets.TELEGRAM_CHAT_ID}}
        token: ${{secrets.TELEGRAM_TOKEN}}
        message: ${{job.status}}
    
